# pessoa = input("Digite o nome da pessoa:")
# print("Boa noite", pessoa)
# idade = input("Qual sua idade?") 
# print("Nossa! você ja tem", idade, "anos")
# email = input("Qual é o seu e-mail?")
# print("seu endereço é? ", email)
numero = input("digite um número: ")
outroNumero = input("digite um outro número:")
print("A soma é ", float(numero) + float(outroNumero))